ps2gg/ps2.gg

- README.md
- docs/Backend.md
- docs/Real-time.md
This PR explains how to create a backend service from start to finish.
It also improves the microservice section in the main Readme.
> docs: Add backend docs, improve readme

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/staging.yml
- build.sh
- deploy.sh
This PR allows us to automatically deploy changes on `master` to our Early Access channels. Manual build/deploy workflows for various environments have been added too. Including production!
> cd: Add automatic staging and manual build/deploy workflows

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Github Templates
Adds templates for descriptive issue and PR descriptions.
> meta: Add issue and pull request template

- services/jaeger/src/infrastructure/SlashCommand/Verify.ts
- services/peepo/src/application/Query/GetAlts.ts
- services/peepo/src/domain/Embed/AltMatch.ts
- services/peepo/src/infrastructure/SlashCommand/Alt.ts
This PR reintroduces the `full` option in Big Peepo.
> feat(peepo): Reimplement `full` option

- .github/workflows/build.yml
- .github/workflows/staging.yml
> fix: Bump command timeout to 60m in build steps

- .github/workflows/build.yml
- .github/workflows/push.yml
> ci(push): Add build step

- libs/alts/types/src/lib/alts.ts
- libs/alts/ws/src/lib/Client.ts
- libs/friends/client/src/lib/FriendsClient.ts
- libs/friends/types/src/lib/Friends.ts
- services/friends/src/application/ApplicationModule.ts
- services/friends/src/application/Command/PopulateFriends.ts
- services/friends/src/application/Command/SetFriends.ts
- services/friends/src/application/Query/GetFriends.ts
- services/friends/src/application/Query/GetMultiple.ts
- services/friends/src/domain/Entity/FriendsEntity.ts
- services/friends/src/infrastructure/Controller/FriendsController.ts
- services/friends/src/infrastructure/TypeOrm/Repository/FriendsRepository.ts
- services/peepo/src/application/Command/ValidateVerification.ts
- services/peepo/src/application/Query/GetAltIds.ts
- services/peepo/src/application/Query/GetAltWideFriends.ts
- services/peepo/src/application/Query/GetFriends.ts
- services/peepo/src/application/Query/GetOnlinePlayer.ts
- services/peepo/src/domain/Embed/SeshFriendsEmbed.ts
- services/peepo/src/domain/Embed/VerifyHintEmbed.ts
- services/peepo/src/domain/Embed/VerifyPlayerEmbed.ts
- services/peepo/src/domain/Meta/Sesh.ts
- services/peepo/src/infrastructure/SlashCommand/Notify.ts
- services/peepo/src/infrastructure/SlashCommand/Sesh.ts
Friend Entity's have their primary column changed from `character_id` to `id`. Should auto-migrate, but we can just drop the database if necessary. Nothing important has been stored yet.
Resolves #71
Resolves #72 
Resolves #73
> feat: Prepare sesh command for early access release

- services/peepo/src/domain/Embed/FriendsEmbed.ts
- services/peepo/src/domain/Meta/Friends.ts
- services/peepo/src/infrastructure/SlashCommand/Friends.ts
- services/peepo/src/main.ts
> feat: Created Friends Command for Peepo

- services/peepo/src/infrastructure/SlashCommand/Sesh.ts
> fix: Allow multiple dev instances to respond to commands

- services/peepo/src/domain/Embed/FriendsEmbed.ts
- services/peepo/src/domain/Embed/VerifiedCharactersEmbed.ts
- services/peepo/src/domain/Meta/WhoAmI.ts
- services/peepo/src/infrastructure/SlashCommand/Friends.ts
- services/peepo/src/infrastructure/SlashCommand/WhoAmI.ts
- services/peepo/src/main.ts
> Feat(peepo): Added whoami Command

- docker/compose/generate-strings.ts
- docker/compose/generate.ts
> fix: Exempt peepo from healthcheck conditions

- services/peepo/src/domain/Embed/VerifiedCharactersEmbed.ts
> style(peepo): Improve whoami embed UI

- services/jaeger/src/application/Query/GetLinkedUser.ts
- services/jaeger/src/domain/Components/WhoIsSelect.ts
- services/jaeger/src/domain/Embed/VerifiedCharactersEmbed.ts
- services/jaeger/src/domain/Embed/WhoIsEmbed.ts
- services/jaeger/src/domain/Meta/WhoIs.ts
- services/jaeger/src/infrastructure/SlashCommand/WhoAmI.ts
- services/jaeger/src/infrastructure/SlashCommand/WhoIs.ts
- services/jaeger/src/main.ts
- services/peepo/src/domain/Embed/VerifiedCharactersEmbed.ts
- services/peepo/src/domain/Meta/Alt.ts
- services/peepo/src/domain/Meta/Setup.ts
- services/peepo/src/domain/Meta/SetupEarlyAccess.ts
- services/peepo/src/infrastructure/SlashCommand/WhoAmI.ts
> feat: Add whois command to Jaeger Bot

- services/peepo/src/application/Query/GetAltIds.ts
- services/peepo/src/application/Query/GetAltWideFriends.ts
- services/peepo/src/application/Query/GetAltWideSesh.ts
- services/peepo/src/application/Query/GetOnlineFriends.ts
- services/peepo/src/application/Query/GetOnlinePlayer.ts
- services/peepo/src/application/Query/GetOnlinePlayers.ts
- services/peepo/src/application/Query/GetSesh.ts
- services/peepo/src/domain/Embed/FriendsEmbed.ts
- services/peepo/src/domain/Meta/Friends.ts
- services/peepo/src/infrastructure/SlashCommand/Friends.ts
- services/peepo/src/infrastructure/SlashCommand/Sesh.ts
> patch: Show original friend's name on matched results

- services/peepo/src/application/Query/GetAltWideSesh.ts
- services/peepo/src/application/Query/GetSesh.ts
- services/peepo/src/domain/Embed/FriendsEmbed.ts
- services/peepo/src/domain/Embed/Notify.ts
- services/peepo/src/domain/Embed/SeshEmbed.ts
- services/peepo/src/domain/Meta/Friends.ts
- services/peepo/src/domain/Meta/Notify.ts
- services/peepo/src/domain/Meta/Sesh.ts
- services/peepo/src/domain/Meta/Verify.ts
- services/peepo/src/infrastructure/SlashCommand/Friends.ts
Resolves #102 
Addresses minor rebrand for notify command in #104
> patch: Improve wording in peepo's commands

- libs/census/collections/src/lib/player.ts
- libs/players/types/src/lib/Player.ts
- services/players/src/application/Command/PopulatePlayer.ts
- services/players/src/application/Command/PopulatePlayerByName.ts
- services/players/src/domain/Entity/PlayerEntity.ts
The players db will have to be dropped and / or repopulated.
Adds server ids to players (Resolves #100)
> feat(players): Add server id to player

- .dockerignore
- build.sh
- docker/Dockerfile.prod
- docker/Dockerfile.staging
- docker/compose/generate-strings.ts
Reduces the time to build production docker images from around 10 minutes to 1 minute
(Resolves #110)
> perf: Reduce time to build docker images

- .github/workflows/push.yml
- libs/alts/types/src/lib/alts.ts
- libs/alts/ws/src/lib/Client.ts
- libs/events/types/src/lib/SubscribableEntity.ts
- libs/events/ws/src/lib/WebSocketClient.ts
- services/peepo/src/application/Query/GetAltIds.ts
- services/peepo/src/application/Query/GetAltWideFriends.ts
- services/peepo/src/application/Query/GetPopulationSubscriptionIds.ts
- services/peepo/src/application/Query/GetSubscription.ts
- services/peepo/src/domain/Embed/FriendsEmbed.ts
- services/peepo/src/domain/Embed/SeshEmbed.ts
- services/peepo/src/domain/Embed/VerifyPlayerEmbed.ts
- services/peepo/src/domain/Meta/Friends.ts
- services/peepo/src/infrastructure/SlashCommand/Friends.ts
Uses new preprocessed alt matches for the friends lookup (Resolves #114)
> perf(peepo): Use rolling ids for friends alt lookup

- libs/alts/types/src/lib/alts.ts
- services/peepo/src/application/Query/GetAltIds.ts
- services/peepo/src/application/Query/GetAltWideFriends.ts
- services/peepo/src/application/Query/GetAltWideSesh.ts
- services/peepo/src/application/Query/GetFriendsWithParents.ts
- services/peepo/src/application/Query/GetOnlinePlayers.ts
- services/peepo/src/application/Query/GetSesh.ts
- services/peepo/src/domain/Embed/SeshEmbed.ts
Fixes a bug where friend's original character name wouldn't be attached to the player name.
> refactor: Fix parent matching in friends retrieval, Simplify parent matching process

- services/peepo/src/domain/Embed/SeshEmbed.ts
Cuts off friends at their name (Resolves #127)
> fix(peepo): Cut off strings at username, sort friends

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/deploy.yml
- .github/workflows/draft.yml
- docs/First-Time-Setup.md
- docs/README.md
- docs/Workflow.md
> ci: Optimize github workflow
